Bug: missing imports in component index.scss files (#1306)
* Bug: missing imports in component index.scss files

Several components were missing the vf-global-variables from their index.scss file, resulting in this on the compontent css build:

```
[18:28:47] Starting 'vf-css:generate-component-css'...
[18:28:47] Finished 'vf-css:generate-component-css' after 1.29 ms
Error: Undefined variable.
  ╷
6 │ @mixin set-type($font-size, $font-family: $global-font-family, $custom-margin-bottom: auto) {
  │                                           ^^^^^^^^^^^^^^^^^^^
  ╵
  ../../components/vf-sass-config/mixins/_typography.scss 6:43  set-type()
  ../../components/vf-heading/vf-heading.scss 17:3              @import
  ../../components/vf-section-header/index.scss 9:9             root stylesheet
Error: Undefined variable.
   ╷
22 │     @if $vf-include-normalisations == true {
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  ../../components/vf-sass-config/mixins/_typography.scss 22:9    set-type()
...
```

This resolves that.

* Add changelogs